language: objective-c
osx_image: xcode6.4
script:
    - xcodebuild -project Objc/PonyDebugger.xcodeproj -scheme PonyDebugger -sdk iphonesimulator -configuration Debug -PBXBuildsContinueAfterErrors=0 ACTIVE_ARCH_ONLY=0 build
